# Generated by Django 2.1.5 on 2019-02-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='appbasic/profile_pics_dir'),
        ),
    ]
