# Generated by Django 2.1.5 on 2019-02-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasic', '0002_auto_20190204_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics_dir'),
        ),
    ]
